// @ts-nocheck
// Opens ONE reviewable adoption issue when semantic content changed
// (SOURCE_MOVED_CONTENT_CHANGED / STALE). Auto-report, never auto-update:
// pins are adopted explicitly via scripts/adopt-source.mjs + PR (ADR-004).
// Idempotent: skips if an open issue with the same head exists.
import { readFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('..', import.meta.url));
const state = JSON.parse(readFileSync(root + '/public/source-state.json', 'utf8'));
const changed = state.sources.filter((s) =>
  s.status === 'SOURCE_MOVED_CONTENT_CHANGED' || s.status === 'STALE');
if (!changed.length) { console.log('no semantic drift — no issue'); process.exit(0); }
const head = `semantic drift: ${changed.length} source(s) changed content`;
const existing = execSync(`gh issue list -R Aftergraph/docs --state open --json title --search "semantic drift in:title"`, { encoding: 'utf8' });
if (JSON.parse(existing).some((i) => i.title === head)) {
  console.log('adoption issue already open — skipping');
  process.exit(0);
}
const rows = changed.map((s) => {
  const arts = (s.artifacts || []).filter((a) => a.changed).map((a) => `- \`${a.path}\`: \`${(a.pinned_blob || '').slice(0, 8)}\` → \`${(a.live_blob || 'unknown').slice(0, 8)}\``).join('\n');
  return `### ${s.repository}\n- status: **${s.status}**\n- pinned: \`${s.pinned_sha}\`\n- remote: \`${s.remote_sha}\`\n- changed artifacts:\n${arts || '- (artifact-level detail unverified)'}`;
}).join('\n\n');
const body = `Automatic Live Truth verifier found semantic content drift. Pin adoption is a **manual, reviewable change** — do not auto-pin (ADR-004).

Run after review:
\`\`\`
node scripts/adopt-source.mjs Aftergraph/<repo> <new-full-sha>
\`\`\`

Checked at: ${state.checked_at}

${rows}

_Issue generated by knowledge-plane-verifier. Report-only: repositories own truth, evidence owns claim strength._`;
execSync(`gh issue create -R Aftergraph/docs --title ${JSON.stringify(head)} --body ${JSON.stringify(body)}`, { stdio: 'inherit' });
console.log('adoption issue created');